
server:
  port: 8080
spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: shopbanhang
  datasource:
    url: jdbc:postgresql://localhost:5432/shopbanhang
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 20
      order_inserts: true
      order_updates: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: cuongssdz1@gmail.com
    password: cwqlwpquczqlppnp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  security:
    allowedOrigins:
      - http://localhost:5173
      - http://localhost:3000
      - http://localhost:4200
    publicEndpoints:
      - /api/v1/auth/**
      - /api/v1/docs/**
      - /swagger-ui.html
      - /swagger-ui/**
      - /api/v1/books/**
      - /api/books/**
      - /api/v1/categories/**
      - /api/categories/**
      - /api/v1/users/register
      - /api/v1/users/forgot-password
      - /api/v1/users/reset-password
      - /api/v1/payment/**

jwt:
  secretKey: c2hvcGJhbmhhbmcxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY=
  accessToken:
    expiration: 86400000
  refreshToken:
    expiration: 604800000

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: 12345678
  bucket: shopbanhang

# VNPay configuration
payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:5173/payment/vn-pay-callback
    tmnCode: VOCHJPXX
    secretKey: Y01LSL5Y22IKR7EA7AO2LLKMXXQTABIT
    version: 2.1.0
    command: pay
    orderType: other
