server:
  port: 8080
spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: shopbanhang
  datasource:
    url: jdbc:postgresql://localhost:5432/shopbanhang
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 20
      order_inserts: true
      order_updates: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    google:
      genai:
        api-key: ${AI_API_KEY:}
        model: ${GEMINI_MODEL:gemini-3.0-flash}
app:
  security:
    allowedOrigins:
      - http://localhost:5173
      - http://localhost:3000
      - http://localhost:4200
    publicEndpoints:
      - /api/v1/auth/**
      - /api/v1/docs/**
      - /swagger-ui.html
      - /swagger-ui/**
      - /api/v1/books/**
      - /api/books/**
      - /api/v1/categories/**
      - /api/categories/**
      - /api/v1/users/register
      - /api/v1/users/forgot-password
      - /api/v1/users/reset-password
      - /api/v1/payment/**
      - /api/v1/faqs/**
      - /api/faqs/**
      - /api/v1/chatbot/**
      - /api/chatbot/**

jwt:
  secretKey: ${JWT_SECRET}
  accessToken:
    expiration: 86400000
  refreshToken:
    expiration: 604800000

minio:
  url: http://localhost:9000
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:12345678}
  bucket: shopbanhang

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:5173/payment/vn-pay-callback
    tmnCode: ${VNPAY_TMN_CODE}
    secretKey: ${VNPAY_SECRET_KEY}
    version: 2.1.0
    command: pay
    orderType: other